name: publish

on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - uses: BrycensRanch/read-properties-action@v1
        id: props
        with:
          file: gradle.properties
          all: true

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ steps.props.outputs.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/${{ steps.props.outputs.archives_base_name }}-${{ github.event.release.tag_name }}.jar
            build/libs/${{ steps.props.outputs.archives_base_name }}-${{ github.event.release.tag_name }}-sources.jar

          version: ${{ github.event.release.tag_name }}

          version-type: beta
          loaders: |
            fabric

          game-versions: ${{ steps.props.outputs.minecraft_version_range }}
          game-version-filter: releases

          dependencies: |
            fabric-api

          java: |
            21

          retry-attempts: 0
          fail-mode: skip

      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "build/libs/*"
          repo-token: ${{ secrets.GH_TOKEN }}
